### ISSUE TITLE
Bypass mode protocol restore

### ISSUE THREAD

**Issue by ygm521** [dpdkcap/dpdkcap#37]
Hello, I want to implement protocol restore based on NIC bypass mode. For example, if you want to restore the user's http request, smtp mail content, you have no tcp ip reorganization and restore of this code, so I can implement other protocol analysis and extract the desired content. But I hope that traffic above 10g can not be lost. I hope to give some advice, thank you.

**Comment by groud** [comment]
The only way you can do that would be to implement a per-ip split of the packets. IIRC this feature is available at the NIC level (you have a a queue per IP split), but that would require to:
1) Reorganize the code as suggested in my comment on #6. We need each queue to write to a given pool, and X writing core for each of the pool (likely one).
2) Implement support for per-ip split as an option.

**Comment by xaki23** [comment]
Closing this since there have not been updates to this issue in a long time and it is about really old versions of DPDK / dpdkcap. 

i may be missing something here, because wth is "NIC bypass mode"?!
aiui this can be done indirectly via BPF filtering // tasking now (to write the interesting/relevant traffic to files), then use something like tcpflow or wireshark to postprocess the files?
