### ISSUE TITLE
Works but seeing issue

### ISSUE THREAD

**Issue by nmurshed** [dpdkcap/dpdkcap#51]
Hi, 
I am having 2 servers A(process a) - B(process b) where both side DPDK is enabled.
I have udp traffic running (50Kbps or 50Mbps).

What I observe is when the start capturing using dpdkcap : 
 dpdkcap -l 40,42,44,46 -n 4 -- -p 0x1 -w /home/cu1/nmurshed/test4

I get the packet captured, however.. process b on server B stops receiving any packets.
Is it like the packets from DPDK are diverted towards dpdkcap ? Won't both process get the packet ?
Process b  doesn't get any packet even if I stop dpdkcap.

has anyone faced this ?

**Comment by lvpenglive** [comment]
只在一个机器上启动过两个

**Comment by xaki23** [comment]
in general, dpdk applications do not really share an interface easily.
it _would_ be possible to modify dpdkcap for this (using the dpdk multi-process support), but it would also require changes to the other (primary) dpdk application on the port.
closing this for now since it seems like a _really_ advanced/niche feature.
doable, but unlikely to happen unless someone comes up with a really strong usecase/interest.
if you are that person, please reopen this issue or file a new one about it!
